sudo: false

os: linux
dist: trusty

language: generic

addons:
  apt:
    packages:
      - lftp
      - tree

install:
  - wget https://github.com/bbuchfink/diamond/releases/download/v0.9.22/diamond-linux64.tar.gz
  - tar xzf diamond-linux64.tar.gz diamond
  - mkdir -p ~/bin && mv diamond ~/bin
  - export PATH="~/bin:$PATH"

before_script:
  - mkdir /tmp/db

script:
  - make check
  - >-
    bash ncbidl.sh -v -p 2 /tmp/db
    blast/db/vector
    refseq/release/mitochondrion/mitochondrion.1.rna.gbff
  - >-
    bash ucscdl.sh -v -p 2 /tmp/db
    goldenPath/xenTro9/bigZips/refMrna.fa
    goldenPath/xenTro9/bigZips/xenTro9.chrom.sizes
  - >-
    bash diamonddb.sh -v -p 2 /tmp/db
    blast/db/FASTA/pdbaa
    pub/taxonomy/accession2taxid/pdb.accession2taxid
    pub/taxonomy/taxdump
  - >-
    bash ensembldl.sh -v -p 2 /tmp/db
    pub/release-93/fasta/gallus_gallus/dna/Gallus_gallus.Gallus_gallus-5.0.dna.chromosome.3
    pub/release-93/bed/ensembl-compara/70_mammals.gerp_constrained_element/gerp_constrained_elements.bos_taurus
    pub/pre/fasta/cdna/felis_catus/fcatus_cat_protein_cdna
  - >-
    bash ensembldl.sh -g -v -p 2 /tmp/db
    pub/release-42/metazoa/fasta/helobdella_robusta/ncrna/Helobdella_robusta.Helro1.ncrna.fa
  - >-
    bash ebidl.sh -v -p 2 /tmp/db
    pub/databases/gencode/Gencode_human/release_28/gencode.v28.metadata.Entrez
  - tree -a /tmp/db
